spring:
  datasource:
    url: jdbc:mysql://localhost:13306/testdb?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: # optional
  jpa:
    hibernate:
      ddl-auto: create

server:
  port: 10000